### ISSUE TITLE
Automatically replace PYOPENCL_CTX="port:pthread" with port:cpu for pocl-4.0

### ISSUE THREAD

**Issue by isuruf** [inducer/ci-support#24]
Since there was a change in name of the device from `pthread` to `cpu`.

**Comment by inducer** [comment]
Thanks for the heads-up!

**Comment by inducer** [comment]
I've decided to make this a problem right away:

https://github.com/illinois-scicomp/machine-shop-maintenance/commit/c15b1887967d2b1ddd291f5a876f820c0eedb287

:slightly_smiling_face:
